apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: busybox-test-app
  namespace: argocd
spec:
  project: default
  source:
    chart: busybox-test-chart
    repoURL: oci://registry-1.docker.io/alkon100
    targetRevision: v1.0.1
    helm:
      version: v3
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
