apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: busybox-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://registry-1.docker.io/alkon100
    chart: busybox-test-chart
    targetRevision: v1.0.1
    helm:
      values: |
        # You can put Helm values here, or leave empty
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
